#!/bin/sh
set -eu

CONFIG_DIR="${OPENCONTEXT7_CONFIG_DIR:-/config}"
DATA_DIR="${OPENCONTEXT7_DATA_DIR:-/data}"
CONFIG_PATH="${OPENCONTEXT7_CONFIG:-$CONFIG_DIR/config.yaml}"

OPENCONTEXT7_HOST="${OPENCONTEXT7_HOST:-0.0.0.0}"
OPENCONTEXT7_PORT="${OPENCONTEXT7_PORT:-8080}"
OPENCONTEXT7_TRANSPORT="${OPENCONTEXT7_TRANSPORT:-http}"
OPENCONTEXT7_MAX_LIBRARIES="${OPENCONTEXT7_MAX_LIBRARIES:-1000}"
OPENCONTEXT7_MAX_DOC_SIZE="${OPENCONTEXT7_MAX_DOC_SIZE:-10485760}"
OPENCONTEXT7_ENABLE_AUTH="${OPENCONTEXT7_ENABLE_AUTH:-false}"
OPENCONTEXT7_API_KEYS="${OPENCONTEXT7_API_KEYS:-}"
OPENCONTEXT7_ALLOWED_IPS="${OPENCONTEXT7_ALLOWED_IPS:-0.0.0.0}"
OPENCONTEXT7_GIT_AUTOSYNC="${OPENCONTEXT7_GIT_AUTOSYNC:-false}"
OPENCONTEXT7_GIT_REPOS_FILE="${OPENCONTEXT7_GIT_REPOS_FILE:-$DATA_DIR/git_repos.json}"
OPENCONTEXT7_GIT_DEFAULT_BRANCH="${OPENCONTEXT7_GIT_DEFAULT_BRANCH:-main}"
OPENCONTEXT7_GIT_SYNC_MINUTES="${OPENCONTEXT7_GIT_SYNC_MINUTES:-15}"
OPENCONTEXT7_GIT_BOOTSTRAP="${OPENCONTEXT7_GIT_BOOTSTRAP:-true}"
OPENCONTEXT7_ENABLE_BACKUPS="${OPENCONTEXT7_ENABLE_BACKUPS:-false}"
OPENCONTEXT7_BACKUP_DIR="${OPENCONTEXT7_BACKUP_DIR:-$DATA_DIR/backups}"
OPENCONTEXT7_BACKUP_RETENTION_DAYS="${OPENCONTEXT7_BACKUP_RETENTION_DAYS:-7}"
OPENCONTEXT7_BACKUP_MAX_SNAPSHOTS="${OPENCONTEXT7_BACKUP_MAX_SNAPSHOTS:-10}"
OPENCONTEXT7_MULTI_USER="${OPENCONTEXT7_MULTI_USER:-false}"
OPENCONTEXT7_USERS_FILE="${OPENCONTEXT7_USERS_FILE:-$DATA_DIR/users.json}"
OPENCONTEXT7_ROLES_FILE="${OPENCONTEXT7_ROLES_FILE:-$DATA_DIR/roles.json}"
OPENCONTEXT7_DEFAULT_ROLE="${OPENCONTEXT7_DEFAULT_ROLE:-viewer}"
OPENCONTEXT7_ENFORCE_LIBRARY_SCOPE="${OPENCONTEXT7_ENFORCE_LIBRARY_SCOPE:-false}"

mkdir -p "$CONFIG_DIR" "$DATA_DIR"
mkdir -p "$(dirname "$OPENCONTEXT7_GIT_REPOS_FILE")"
mkdir -p "$(dirname "$OPENCONTEXT7_USERS_FILE")"
mkdir -p "$(dirname "$OPENCONTEXT7_ROLES_FILE")"
mkdir -p "$OPENCONTEXT7_BACKUP_DIR"

lower_bool() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

normalize_bool() {
  case "$(lower_bool "$1")" in
    true|1|yes|y) printf 'true' ;;
    *) printf 'false' ;;
  esac
}

format_csv_list() {
  value="$1"
  if [ -z "$value" ]; then
    printf '[]'
    return
  fi
  first=1
  printf '['
  old_ifs=$IFS
  IFS=','
  for item in $value; do
    trimmed=$(printf '%s' "$item" | sed 's/^ *//;s/ *$//')
    if [ -z "$trimmed" ]; then
      continue
    fi
    if [ "$first" -eq 1 ]; then
      printf '"%s"' "$trimmed"
      first=0
    else
      printf ', "%s"' "$trimmed"
    fi
  done
  IFS=$old_ifs
  if [ "$first" -eq 1 ]; then
    printf ']'
  else
    printf ']'
  fi
}

OPENCONTEXT7_ENABLE_AUTH="$(normalize_bool "$OPENCONTEXT7_ENABLE_AUTH")"
OPENCONTEXT7_GIT_AUTOSYNC="$(normalize_bool "$OPENCONTEXT7_GIT_AUTOSYNC")"
OPENCONTEXT7_GIT_BOOTSTRAP="$(normalize_bool "$OPENCONTEXT7_GIT_BOOTSTRAP")"
OPENCONTEXT7_ENABLE_BACKUPS="$(normalize_bool "$OPENCONTEXT7_ENABLE_BACKUPS")"
OPENCONTEXT7_MULTI_USER="$(normalize_bool "$OPENCONTEXT7_MULTI_USER")"
OPENCONTEXT7_ENFORCE_LIBRARY_SCOPE="$(normalize_bool "$OPENCONTEXT7_ENFORCE_LIBRARY_SCOPE")"

API_KEYS_JSON=$(format_csv_list "$OPENCONTEXT7_API_KEYS")
ALLOWED_IPS_JSON=$(format_csv_list "$OPENCONTEXT7_ALLOWED_IPS")

if [ ! -f "$CONFIG_PATH" ]; then
  cat >"$CONFIG_PATH" <<EOF
server:
  host: ${OPENCONTEXT7_HOST}
  port: ${OPENCONTEXT7_PORT}
  transport: ${OPENCONTEXT7_TRANSPORT}

storage:
  dataDir: ${DATA_DIR}
  maxLibraries: ${OPENCONTEXT7_MAX_LIBRARIES}
  maxDocSize: ${OPENCONTEXT7_MAX_DOC_SIZE}

security:
  enableAuth: ${OPENCONTEXT7_ENABLE_AUTH}
  apiKeys: ${API_KEYS_JSON}
  allowedIps: ${ALLOWED_IPS_JSON}

integration:
  enableAutoSync: ${OPENCONTEXT7_GIT_AUTOSYNC}
  reposFile: ${OPENCONTEXT7_GIT_REPOS_FILE}
  defaultBranch: ${OPENCONTEXT7_GIT_DEFAULT_BRANCH}
  syncIntervalMinutes: ${OPENCONTEXT7_GIT_SYNC_MINUTES}
  autoBootstrap: ${OPENCONTEXT7_GIT_BOOTSTRAP}

backup:
  enableBackups: ${OPENCONTEXT7_ENABLE_BACKUPS}
  backupDir: ${OPENCONTEXT7_BACKUP_DIR}
  retentionDays: ${OPENCONTEXT7_BACKUP_RETENTION_DAYS}
  maxSnapshots: ${OPENCONTEXT7_BACKUP_MAX_SNAPSHOTS}

access:
  multiUserEnabled: ${OPENCONTEXT7_MULTI_USER}
  usersFile: ${OPENCONTEXT7_USERS_FILE}
  rolesFile: ${OPENCONTEXT7_ROLES_FILE}
  defaultRole: ${OPENCONTEXT7_DEFAULT_ROLE}
  enforceLibraryScope: ${OPENCONTEXT7_ENFORCE_LIBRARY_SCOPE}
EOF
fi

export OPENCONTEXT7_CONFIG="$CONFIG_PATH"
export OPENCONTEXT7_DATA_DIR="$DATA_DIR"
export OPENCONTEXT7_HOST="$OPENCONTEXT7_HOST"
export OPENCONTEXT7_PORT="$OPENCONTEXT7_PORT"
export OPENCONTEXT7_TRANSPORT="$OPENCONTEXT7_TRANSPORT"
export OPENCONTEXT7_ENABLE_AUTH
export OPENCONTEXT7_API_KEYS
export OPENCONTEXT7_ALLOWED_IPS
export OPENCONTEXT7_MAX_LIBRARIES
export OPENCONTEXT7_MAX_DOC_SIZE
export OPENCONTEXT7_GIT_AUTOSYNC
export OPENCONTEXT7_GIT_REPOS_FILE
export OPENCONTEXT7_GIT_DEFAULT_BRANCH
export OPENCONTEXT7_GIT_SYNC_MINUTES
export OPENCONTEXT7_GIT_BOOTSTRAP
export OPENCONTEXT7_ENABLE_BACKUPS
export OPENCONTEXT7_BACKUP_DIR
export OPENCONTEXT7_BACKUP_RETENTION_DAYS
export OPENCONTEXT7_BACKUP_MAX_SNAPSHOTS
export OPENCONTEXT7_MULTI_USER
export OPENCONTEXT7_USERS_FILE
export OPENCONTEXT7_ROLES_FILE
export OPENCONTEXT7_DEFAULT_ROLE
export OPENCONTEXT7_ENFORCE_LIBRARY_SCOPE

if [ "$#" -eq 0 ] || [ "$1" = "server" ]; then
  exec opencontext7 server
else
  exec opencontext7 "$@"
fi
