#!/bin/sh
set -eu

CONFIG_DIR="${MINERU_PDFHUB_CONFIG_DIR:-/config}"
DATA_DIR="${MINERU_PDFHUB_DATA_DIR:-/data}"
CONFIG_PATH="${MINERU_PDFHUB_CONFIG:-$CONFIG_DIR/config.yaml}"

MINERU_PDFHUB_HOST="${MINERU_PDFHUB_HOST:-0.0.0.0}"
MINERU_PDFHUB_PORT="${MINERU_PDFHUB_PORT:-8080}"
MINERU_PDFHUB_TRANSPORT="${MINERU_PDFHUB_TRANSPORT:-http}"
MINERU_PDFHUB_MAX_LIBRARIES="${MINERU_PDFHUB_MAX_LIBRARIES:-1000}"
MINERU_PDFHUB_MAX_DOC_SIZE="${MINERU_PDFHUB_MAX_DOC_SIZE:-10485760}"
MINERU_PDFHUB_ENABLE_AUTH="${MINERU_PDFHUB_ENABLE_AUTH:-false}"
MINERU_PDFHUB_API_KEYS="${MINERU_PDFHUB_API_KEYS:-}"
MINERU_PDFHUB_ALLOWED_IPS="${MINERU_PDFHUB_ALLOWED_IPS:-0.0.0.0}"
MINERU_PDFHUB_GIT_AUTOSYNC="${MINERU_PDFHUB_GIT_AUTOSYNC:-false}"
MINERU_PDFHUB_GIT_REPOS_FILE="${MINERU_PDFHUB_GIT_REPOS_FILE:-$DATA_DIR/git_repos.json}"
MINERU_PDFHUB_GIT_DEFAULT_BRANCH="${MINERU_PDFHUB_GIT_DEFAULT_BRANCH:-main}"
MINERU_PDFHUB_GIT_SYNC_MINUTES="${MINERU_PDFHUB_GIT_SYNC_MINUTES:-15}"
MINERU_PDFHUB_GIT_BOOTSTRAP="${MINERU_PDFHUB_GIT_BOOTSTRAP:-true}"
MINERU_PDFHUB_ENABLE_BACKUPS="${MINERU_PDFHUB_ENABLE_BACKUPS:-false}"
MINERU_PDFHUB_BACKUP_DIR="${MINERU_PDFHUB_BACKUP_DIR:-$DATA_DIR/backups}"
MINERU_PDFHUB_BACKUP_RETENTION_DAYS="${MINERU_PDFHUB_BACKUP_RETENTION_DAYS:-7}"
MINERU_PDFHUB_BACKUP_MAX_SNAPSHOTS="${MINERU_PDFHUB_BACKUP_MAX_SNAPSHOTS:-10}"
MINERU_PDFHUB_MULTI_USER="${MINERU_PDFHUB_MULTI_USER:-false}"
MINERU_PDFHUB_USERS_FILE="${MINERU_PDFHUB_USERS_FILE:-$DATA_DIR/users.json}"
MINERU_PDFHUB_ROLES_FILE="${MINERU_PDFHUB_ROLES_FILE:-$DATA_DIR/roles.json}"
MINERU_PDFHUB_DEFAULT_ROLE="${MINERU_PDFHUB_DEFAULT_ROLE:-viewer}"
MINERU_PDFHUB_ENFORCE_LIBRARY_SCOPE="${MINERU_PDFHUB_ENFORCE_LIBRARY_SCOPE:-false}"

mkdir -p "$CONFIG_DIR" "$DATA_DIR"
mkdir -p "$(dirname "$MINERU_PDFHUB_GIT_REPOS_FILE")"
mkdir -p "$(dirname "$MINERU_PDFHUB_USERS_FILE")"
mkdir -p "$(dirname "$MINERU_PDFHUB_ROLES_FILE")"
mkdir -p "$MINERU_PDFHUB_BACKUP_DIR"

lower_bool() {
  printf '%s' "$1" | tr '[:upper:]' '[:lower:]'
}

normalize_bool() {
  case "$(lower_bool "$1")" in
    true|1|yes|y) printf 'true' ;;
    *) printf 'false' ;;
  esac
}

format_csv_list() {
  value="$1"
  if [ -z "$value" ]; then
    printf '[]'
    return
  fi
  first=1
  printf '['
  old_ifs=$IFS
  IFS=','
  for item in $value; do
    trimmed=$(printf '%s' "$item" | sed 's/^ *//;s/ *$//')
    if [ -z "$trimmed" ]; then
      continue
    fi
    if [ "$first" -eq 1 ]; then
      printf '"%s"' "$trimmed"
      first=0
    else
      printf ', "%s"' "$trimmed"
    fi
  done
  IFS=$old_ifs
  if [ "$first" -eq 1 ]; then
    printf ']'
  else
    printf ']'
  fi
}

MINERU_PDFHUB_ENABLE_AUTH="$(normalize_bool "$MINERU_PDFHUB_ENABLE_AUTH")"
MINERU_PDFHUB_GIT_AUTOSYNC="$(normalize_bool "$MINERU_PDFHUB_GIT_AUTOSYNC")"
MINERU_PDFHUB_GIT_BOOTSTRAP="$(normalize_bool "$MINERU_PDFHUB_GIT_BOOTSTRAP")"
MINERU_PDFHUB_ENABLE_BACKUPS="$(normalize_bool "$MINERU_PDFHUB_ENABLE_BACKUPS")"
MINERU_PDFHUB_MULTI_USER="$(normalize_bool "$MINERU_PDFHUB_MULTI_USER")"
MINERU_PDFHUB_ENFORCE_LIBRARY_SCOPE="$(normalize_bool "$MINERU_PDFHUB_ENFORCE_LIBRARY_SCOPE")"

API_KEYS_JSON=$(format_csv_list "$MINERU_PDFHUB_API_KEYS")
ALLOWED_IPS_JSON=$(format_csv_list "$MINERU_PDFHUB_ALLOWED_IPS")

if [ ! -f "$CONFIG_PATH" ]; then
  cat >"$CONFIG_PATH" <<EOF
server:
  host: ${MINERU_PDFHUB_HOST}
  port: ${MINERU_PDFHUB_PORT}
  transport: ${MINERU_PDFHUB_TRANSPORT}

storage:
  dataDir: ${DATA_DIR}
  maxLibraries: ${MINERU_PDFHUB_MAX_LIBRARIES}
  maxDocSize: ${MINERU_PDFHUB_MAX_DOC_SIZE}

security:
  enableAuth: ${MINERU_PDFHUB_ENABLE_AUTH}
  apiKeys: ${API_KEYS_JSON}
  allowedIps: ${ALLOWED_IPS_JSON}

integration:
  enableAutoSync: ${MINERU_PDFHUB_GIT_AUTOSYNC}
  reposFile: ${MINERU_PDFHUB_GIT_REPOS_FILE}
  defaultBranch: ${MINERU_PDFHUB_GIT_DEFAULT_BRANCH}
  syncIntervalMinutes: ${MINERU_PDFHUB_GIT_SYNC_MINUTES}
  autoBootstrap: ${MINERU_PDFHUB_GIT_BOOTSTRAP}

backup:
  enableBackups: ${MINERU_PDFHUB_ENABLE_BACKUPS}
  backupDir: ${MINERU_PDFHUB_BACKUP_DIR}
  retentionDays: ${MINERU_PDFHUB_BACKUP_RETENTION_DAYS}
  maxSnapshots: ${MINERU_PDFHUB_BACKUP_MAX_SNAPSHOTS}

access:
  multiUserEnabled: ${MINERU_PDFHUB_MULTI_USER}
  usersFile: ${MINERU_PDFHUB_USERS_FILE}
  rolesFile: ${MINERU_PDFHUB_ROLES_FILE}
  defaultRole: ${MINERU_PDFHUB_DEFAULT_ROLE}
  enforceLibraryScope: ${MINERU_PDFHUB_ENFORCE_LIBRARY_SCOPE}
EOF
fi

export MINERU_PDFHUB_CONFIG="$CONFIG_PATH"
export MINERU_PDFHUB_DATA_DIR="$DATA_DIR"
export MINERU_PDFHUB_HOST="$MINERU_PDFHUB_HOST"
export MINERU_PDFHUB_PORT="$MINERU_PDFHUB_PORT"
export MINERU_PDFHUB_TRANSPORT="$MINERU_PDFHUB_TRANSPORT"
export MINERU_PDFHUB_ENABLE_AUTH
export MINERU_PDFHUB_API_KEYS
export MINERU_PDFHUB_ALLOWED_IPS
export MINERU_PDFHUB_MAX_LIBRARIES
export MINERU_PDFHUB_MAX_DOC_SIZE
export MINERU_PDFHUB_GIT_AUTOSYNC
export MINERU_PDFHUB_GIT_REPOS_FILE
export MINERU_PDFHUB_GIT_DEFAULT_BRANCH
export MINERU_PDFHUB_GIT_SYNC_MINUTES
export MINERU_PDFHUB_GIT_BOOTSTRAP
export MINERU_PDFHUB_ENABLE_BACKUPS
export MINERU_PDFHUB_BACKUP_DIR
export MINERU_PDFHUB_BACKUP_RETENTION_DAYS
export MINERU_PDFHUB_BACKUP_MAX_SNAPSHOTS
export MINERU_PDFHUB_MULTI_USER
export MINERU_PDFHUB_USERS_FILE
export MINERU_PDFHUB_ROLES_FILE
export MINERU_PDFHUB_DEFAULT_ROLE
export MINERU_PDFHUB_ENFORCE_LIBRARY_SCOPE

if [ "$#" -eq 0 ] || [ "$1" = "server" ]; then
  exec mineru-pdfhub server
else
  exec mineru-pdfhub "$@"
fi
